from django.db import models
from django.urls import reverse

class Students(models.Model):
    username = models.CharField('Имя', max_length=120)
    mail = models.EmailField('E-mail', default=0)
    school = models.IntegerField('Школа', default=0)
    level = models.IntegerField('Класс', default=0)
    password1 = models.CharField('Пароль',max_length=50 )
    password2 = models.CharField('Пароль2',max_length=50 )
    fiscul = models.BooleanField('Физ-ра', default=False)
    lit = models.BooleanField('Литература', default=False)
    algebra = models.BooleanField('Алгебра', default=False)
    geomet = models.BooleanField('Геометрия', default=False)
    history = models.BooleanField('История', default=False)
    music = models.BooleanField('Музыка', default=False)
    obg = models.BooleanField('ОБЖ', default=False)
    paiting = models.BooleanField('Рисование', default=False)
    russian = models.BooleanField('Рус-яз', default=False)
    inostr = models.BooleanField('Ин-Яз', default=False)
    technology = models.BooleanField('Технология', default=False)
    geography = models.BooleanField('География', default=False)
    biology = models.BooleanField('Биология', default=False)
    itk = models.BooleanField('Информатика', default=False)
    social = models.BooleanField('Обществознание', default=False)
    drawing = models.BooleanField('Черчение', default=False)
    physics = models.BooleanField('Физика', default=False)
    chemistry = models.BooleanField('Химия', default=False)
    fiscul_t = models.FloatField('Физ-ра--цель', null=True, blank=True, default=None)
    lit_t = models.FloatField('Литература--цель', null=True, blank=True, default=None)
    algebra_t = models.FloatField('Алгебра--цель',null=True, blank=True, default=None)
    geomet_t = models.FloatField('Геометрия--цель',null=True, blank=True, default=None)
    history_t = models.FloatField('История--цель',null=True, blank=True, default=None)
    odg_t = models.FloatField('ОБЖ--цель', null=True, blank=True, default=None)
    music_t = models.FloatField('Музыка--цель', null=True, blank=True, default=None)
    paiting_t = models.FloatField('Рисование--цель', null=True, blank=True, default=None)
    russian_t = models.FloatField('Рус-яз--цель',null=True, blank=True, default=None)
    inostr_t = models.FloatField('Ин-яз--цель',null=True, blank=True, default=None)
    technology_t = models.FloatField('Технология--цель',null=True, blank=True, default=None)
    geography_t = models.FloatField('География--цель', null=True, blank=True, default=None)
    biology_t = models.FloatField('Биология--цель', null=True, blank=True, default=None)
    itk_t = models.FloatField('Информатика--цель', null=True, blank=True, default=None)
    social_t = models.FloatField('Обществознание--цель',null=True, blank=True, default=None)
    drawing_t = models.FloatField('Черчение--цель',null=True, blank=True, default=None)
    physics_t = models.FloatField('Физика--цель',null=True, blank=True, default=None)
    chemistry_t = models.FloatField('Химия--цель', null=True, blank=True, default=None)
    def get_absolute_url(self):
        return reverse("articles:article-detail", kwargs={"id": self.id})


class Mark(models.Model):
    students = models.ForeignKey(Students, on_delete = models.CASCADE)
    mark = models.IntegerField('Оценка', default=0)
    reg = models.IntegerField('Коэффициент', default=0)
    def get_absolute_url(self):
        return reverse("articles:article-detail", kwargs={"id": self.id})